version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aegis_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/documents:/app/documents_storage
      - ./data/vector_store:/app/vector_store
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: aegis_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  documents_storage:
  vector_store:
